-- Seed Districts (İlçeler)
-- Run this in Supabase SQL Editor AFTER running the migrations AND seed-categories-cities.sql
-- Total: ~970 districts across 81 cities

-- Insert Districts (without coordinates for brevity)
INSERT INTO districts (name, slug, city_id) VALUES

-- ADANA (15 ilçe)
('Aladağ', 'aladag', (SELECT id FROM cities WHERE slug = 'adana')),
('Ceyhan', 'ceyhan', (SELECT id FROM cities WHERE slug = 'adana')),
('Çukurova', 'cukurova', (SELECT id FROM cities WHERE slug = 'adana')),
('Feke', 'feke', (SELECT id FROM cities WHERE slug = 'adana')),
('İmamoğlu', 'imamoglu', (SELECT id FROM cities WHERE slug = 'adana')),
('Karaisalı', 'karaisali', (SELECT id FROM cities WHERE slug = 'adana')),
('Karataş', 'karatas', (SELECT id FROM cities WHERE slug = 'adana')),
('Kozan', 'kozan', (SELECT id FROM cities WHERE slug = 'adana')),
('Pozantı', 'pozanti', (SELECT id FROM cities WHERE slug = 'adana')),
('Saimbeyli', 'saimbeyli', (SELECT id FROM cities WHERE slug = 'adana')),
('Sarıçam', 'saricam', (SELECT id FROM cities WHERE slug = 'adana')),
('Seyhan', 'seyhan', (SELECT id FROM cities WHERE slug = 'adana')),
('Tufanbeyli', 'tufanbeyli', (SELECT id FROM cities WHERE slug = 'adana')),
('Yumurtalık', 'yumurtalik', (SELECT id FROM cities WHERE slug = 'adana')),
('Yüreğir', 'yuregir', (SELECT id FROM cities WHERE slug = 'adana')),

-- ADIYAMAN (9 ilçe)
('Besni', 'besni', (SELECT id FROM cities WHERE slug = 'adiyaman')),
('Çelikhan', 'celikhan', (SELECT id FROM cities WHERE slug = 'adiyaman')),
('Gerger', 'gerger', (SELECT id FROM cities WHERE slug = 'adiyaman')),
('Gölbaşı', 'golbasi-adiyaman', (SELECT id FROM cities WHERE slug = 'adiyaman')),
('Kahta', 'kahta', (SELECT id FROM cities WHERE slug = 'adiyaman')),
('Merkez', 'merkez-adiyaman', (SELECT id FROM cities WHERE slug = 'adiyaman')),
('Samsat', 'samsat', (SELECT id FROM cities WHERE slug = 'adiyaman')),
('Sincik', 'sincik', (SELECT id FROM cities WHERE slug = 'adiyaman')),
('Tut', 'tut', (SELECT id FROM cities WHERE slug = 'adiyaman')),

-- AFYONKARAHİSAR (18 ilçe)
('Başmakçı', 'basmakci', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Bayat', 'bayat-afyon', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Bolvadin', 'bolvadin', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Çay', 'cay', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Çobanlar', 'cobanlar', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Dazkırı', 'dazkiri', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Dinar', 'dinar', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Emirdağ', 'emirdag', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Evciler', 'evciler', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Hocalar', 'hocalar', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('İhsaniye', 'ihsaniye', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('İscehisar', 'iscehisar', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Kızılören', 'kiziloren', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Merkez', 'merkez-afyon', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Sandıklı', 'sandikli', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Sinanpaşa', 'sinanpasa', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Sultandağı', 'sultandagi', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),
('Şuhut', 'suhut', (SELECT id FROM cities WHERE slug = 'afyonkarahisar')),

-- AĞRI (8 ilçe)
('Diyadin', 'diyadin', (SELECT id FROM cities WHERE slug = 'agri')),
('Doğubayazıt', 'dogubayazit', (SELECT id FROM cities WHERE slug = 'agri')),
('Eleşkirt', 'eleskirt', (SELECT id FROM cities WHERE slug = 'agri')),
('Hamur', 'hamur', (SELECT id FROM cities WHERE slug = 'agri')),
('Merkez', 'merkez-agri', (SELECT id FROM cities WHERE slug = 'agri')),
('Patnos', 'patnos', (SELECT id FROM cities WHERE slug = 'agri')),
('Taşlıçay', 'taslicay', (SELECT id FROM cities WHERE slug = 'agri')),
('Tutak', 'tutak', (SELECT id FROM cities WHERE slug = 'agri')),

-- AKSARAY (8 ilçe)
('Ağaçören', 'agacoren', (SELECT id FROM cities WHERE slug = 'aksaray')),
('Eskil', 'eskil', (SELECT id FROM cities WHERE slug = 'aksaray')),
('Gülağaç', 'gulagac', (SELECT id FROM cities WHERE slug = 'aksaray')),
('Güzelyurt', 'guzelyurt', (SELECT id FROM cities WHERE slug = 'aksaray')),
('Merkez', 'merkez-aksaray', (SELECT id FROM cities WHERE slug = 'aksaray')),
('Ortaköy', 'ortakoy-aksaray', (SELECT id FROM cities WHERE slug = 'aksaray')),
('Sarıyahşi', 'sariyahsi', (SELECT id FROM cities WHERE slug = 'aksaray')),
('Sultanhanı', 'sultanhani', (SELECT id FROM cities WHERE slug = 'aksaray')),

-- AMASYA (7 ilçe)
('Göynücek', 'goynucek', (SELECT id FROM cities WHERE slug = 'amasya')),
('Gümüşhacıköy', 'gumushacikoy', (SELECT id FROM cities WHERE slug = 'amasya')),
('Hamamözü', 'hamamozu', (SELECT id FROM cities WHERE slug = 'amasya')),
('Merkez', 'merkez-amasya', (SELECT id FROM cities WHERE slug = 'amasya')),
('Merzifon', 'merzifon', (SELECT id FROM cities WHERE slug = 'amasya')),
('Suluova', 'suluova', (SELECT id FROM cities WHERE slug = 'amasya')),
('Taşova', 'tasova', (SELECT id FROM cities WHERE slug = 'amasya')),

-- ANKARA (25 ilçe)
('Akyurt', 'akyurt', (SELECT id FROM cities WHERE slug = 'ankara')),
('Altındağ', 'altindag', (SELECT id FROM cities WHERE slug = 'ankara')),
('Ayaş', 'ayas', (SELECT id FROM cities WHERE slug = 'ankara')),
('Bala', 'bala', (SELECT id FROM cities WHERE slug = 'ankara')),
('Beypazarı', 'beypazari', (SELECT id FROM cities WHERE slug = 'ankara')),
('Çamlıdere', 'camlidere', (SELECT id FROM cities WHERE slug = 'ankara')),
('Çankaya', 'cankaya', (SELECT id FROM cities WHERE slug = 'ankara')),
('Çubuk', 'cubuk', (SELECT id FROM cities WHERE slug = 'ankara')),
('Elmadağ', 'elmadag', (SELECT id FROM cities WHERE slug = 'ankara')),
('Etimesgut', 'etimesgut', (SELECT id FROM cities WHERE slug = 'ankara')),
('Evren', 'evren', (SELECT id FROM cities WHERE slug = 'ankara')),
('Gölbaşı', 'golbasi-ankara', (SELECT id FROM cities WHERE slug = 'ankara')),
('Güdül', 'gudul', (SELECT id FROM cities WHERE slug = 'ankara')),
('Haymana', 'haymana', (SELECT id FROM cities WHERE slug = 'ankara')),
('Kalecik', 'kalecik', (SELECT id FROM cities WHERE slug = 'ankara')),
('Kazan', 'kazan', (SELECT id FROM cities WHERE slug = 'ankara')),
('Keçiören', 'kecioren', (SELECT id FROM cities WHERE slug = 'ankara')),
('Kızılcahamam', 'kizilcahamam', (SELECT id FROM cities WHERE slug = 'ankara')),
('Mamak', 'mamak', (SELECT id FROM cities WHERE slug = 'ankara')),
('Nallıhan', 'nallihan', (SELECT id FROM cities WHERE slug = 'ankara')),
('Polatlı', 'polatli', (SELECT id FROM cities WHERE slug = 'ankara')),
('Pursaklar', 'pursaklar', (SELECT id FROM cities WHERE slug = 'ankara')),
('Sincan', 'sincan', (SELECT id FROM cities WHERE slug = 'ankara')),
('Şereflikoçhisar', 'sereflikochisir', (SELECT id FROM cities WHERE slug = 'ankara')),
('Yenimahalle', 'yenimahalle', (SELECT id FROM cities WHERE slug = 'ankara')),

-- ANTALYA (19 ilçe)
('Akseki', 'akseki', (SELECT id FROM cities WHERE slug = 'antalya')),
('Aksu', 'aksu-antalya', (SELECT id FROM cities WHERE slug = 'antalya')),
('Alanya', 'alanya', (SELECT id FROM cities WHERE slug = 'antalya')),
('Demre', 'demre', (SELECT id FROM cities WHERE slug = 'antalya')),
('Döşemealtı', 'dosemealti', (SELECT id FROM cities WHERE slug = 'antalya')),
('Elmalı', 'elmali', (SELECT id FROM cities WHERE slug = 'antalya')),
('Finike', 'finike', (SELECT id FROM cities WHERE slug = 'antalya')),
('Gazipaşa', 'gazipasa', (SELECT id FROM cities WHERE slug = 'antalya')),
('Gündoğmuş', 'gundogmus', (SELECT id FROM cities WHERE slug = 'antalya')),
('İbradı', 'ibradi', (SELECT id FROM cities WHERE slug = 'antalya')),
('Kaş', 'kas', (SELECT id FROM cities WHERE slug = 'antalya')),
('Kemer', 'kemer-antalya', (SELECT id FROM cities WHERE slug = 'antalya')),
('Kepez', 'kepez', (SELECT id FROM cities WHERE slug = 'antalya')),
('Konyaaltı', 'konyaalti', (SELECT id FROM cities WHERE slug = 'antalya')),
('Korkuteli', 'korkuteli', (SELECT id FROM cities WHERE slug = 'antalya')),
('Kumluca', 'kumluca', (SELECT id FROM cities WHERE slug = 'antalya')),
('Manavgat', 'manavgat', (SELECT id FROM cities WHERE slug = 'antalya')),
('Muratpaşa', 'muratpasa', (SELECT id FROM cities WHERE slug = 'antalya')),
('Serik', 'serik', (SELECT id FROM cities WHERE slug = 'antalya')),

-- ARDAHAN (6 ilçe)
('Çıldır', 'cildir', (SELECT id FROM cities WHERE slug = 'ardahan')),
('Damal', 'damal', (SELECT id FROM cities WHERE slug = 'ardahan')),
('Göle', 'gole', (SELECT id FROM cities WHERE slug = 'ardahan')),
('Hanak', 'hanak', (SELECT id FROM cities WHERE slug = 'ardahan')),
('Merkez', 'merkez-ardahan', (SELECT id FROM cities WHERE slug = 'ardahan')),
('Posof', 'posof', (SELECT id FROM cities WHERE slug = 'ardahan')),

-- ARTVIN (8 ilçe)
('Ardanuç', 'ardanuc', (SELECT id FROM cities WHERE slug = 'artvin')),
('Arhavi', 'arhavi', (SELECT id FROM cities WHERE slug = 'artvin')),
('Borçka', 'borcka', (SELECT id FROM cities WHERE slug = 'artvin')),
('Hopa', 'hopa', (SELECT id FROM cities WHERE slug = 'artvin')),
('Kemalpaşa', 'kemalpasa-artvin', (SELECT id FROM cities WHERE slug = 'artvin')),
('Merkez', 'merkez-artvin', (SELECT id FROM cities WHERE slug = 'artvin')),
('Murgul', 'murgul', (SELECT id FROM cities WHERE slug = 'artvin')),
('Şavşat', 'savsat', (SELECT id FROM cities WHERE slug = 'artvin')),

-- AYDIN (17 ilçe)
('Bozdoğan', 'bozdogan', (SELECT id FROM cities WHERE slug = 'aydin')),
('Buharkent', 'buharkent', (SELECT id FROM cities WHERE slug = 'aydin')),
('Çine', 'cine', (SELECT id FROM cities WHERE slug = 'aydin')),
('Didim', 'didim', (SELECT id FROM cities WHERE slug = 'aydin')),
('Efeler', 'efeler', (SELECT id FROM cities WHERE slug = 'aydin')),
('Germencik', 'germencik', (SELECT id FROM cities WHERE slug = 'aydin')),
('İncirliova', 'incirliova', (SELECT id FROM cities WHERE slug = 'aydin')),
('Karacasu', 'karacasu', (SELECT id FROM cities WHERE slug = 'aydin')),
('Karpuzlu', 'karpuzlu', (SELECT id FROM cities WHERE slug = 'aydin')),
('Koçarlı', 'kocarli', (SELECT id FROM cities WHERE slug = 'aydin')),
('Köşk', 'kosk', (SELECT id FROM cities WHERE slug = 'aydin')),
('Kuşadası', 'kusadasi', (SELECT id FROM cities WHERE slug = 'aydin')),
('Kuyucak', 'kuyucak', (SELECT id FROM cities WHERE slug = 'aydin')),
('Nazilli', 'nazilli', (SELECT id FROM cities WHERE slug = 'aydin')),
('Söke', 'soke', (SELECT id FROM cities WHERE slug = 'aydin')),
('Sultanhisar', 'sultanhisar', (SELECT id FROM cities WHERE slug = 'aydin')),
('Yenipazar', 'yenipazar-aydin', (SELECT id FROM cities WHERE slug = 'aydin')),

-- BALIKESİR (20 ilçe)
('Altıeylül', 'altieylul', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Ayvalık', 'ayvalik', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Balya', 'balya', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Bandırma', 'bandirma', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Bigadiç', 'bigadic', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Burhaniye', 'burhaniye', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Dursunbey', 'dursunbey', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Edremit', 'edremit-balikesir', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Erdek', 'erdek', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Gömeç', 'gomec', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Gönen', 'gonen', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Havran', 'havran', (SELECT id FROM cities WHERE slug = 'balikesir')),
('İvrindi', 'ivrindi', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Karesi', 'karesi', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Kepsut', 'kepsut', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Manyas', 'manyas', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Marmara', 'marmara', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Savaştepe', 'savastepe', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Sındırgı', 'sindirgi', (SELECT id FROM cities WHERE slug = 'balikesir')),
('Susurluk', 'susurluk', (SELECT id FROM cities WHERE slug = 'balikesir')),

-- BARTIN (4 ilçe)
('Amasra', 'amasra', (SELECT id FROM cities WHERE slug = 'bartin')),
('Kurucaşile', 'kurucasile', (SELECT id FROM cities WHERE slug = 'bartin')),
('Merkez', 'merkez-bartin', (SELECT id FROM cities WHERE slug = 'bartin')),
('Ulus', 'ulus', (SELECT id FROM cities WHERE slug = 'bartin')),

-- BATMAN (6 ilçe)
('Beşiri', 'besiri', (SELECT id FROM cities WHERE slug = 'batman')),
('Gercüş', 'gercus', (SELECT id FROM cities WHERE slug = 'batman')),
('Hasankeyf', 'hasankeyf', (SELECT id FROM cities WHERE slug = 'batman')),
('Kozluk', 'kozluk', (SELECT id FROM cities WHERE slug = 'batman')),
('Merkez', 'merkez-batman', (SELECT id FROM cities WHERE slug = 'batman')),
('Sason', 'sason', (SELECT id FROM cities WHERE slug = 'batman')),

-- BAYBURT (3 ilçe)
('Aydıntepe', 'aydintepe', (SELECT id FROM cities WHERE slug = 'bayburt')),
('Demirözü', 'demirozu', (SELECT id FROM cities WHERE slug = 'bayburt')),
('Merkez', 'merkez-bayburt', (SELECT id FROM cities WHERE slug = 'bayburt')),

-- BİLECİK (8 ilçe)
('Bozüyük', 'bozuyuk', (SELECT id FROM cities WHERE slug = 'bilecik')),
('Gölpazarı', 'golpazari', (SELECT id FROM cities WHERE slug = 'bilecik')),
('İnhisar', 'inhisar', (SELECT id FROM cities WHERE slug = 'bilecik')),
('Merkez', 'merkez-bilecik', (SELECT id FROM cities WHERE slug = 'bilecik')),
('Osmaneli', 'osmaneli', (SELECT id FROM cities WHERE slug = 'bilecik')),
('Pazaryeri', 'pazaryeri', (SELECT id FROM cities WHERE slug = 'bilecik')),
('Söğüt', 'sogut', (SELECT id FROM cities WHERE slug = 'bilecik')),
('Yenipazar', 'yenipazar-bilecik', (SELECT id FROM cities WHERE slug = 'bilecik')),

-- BİNGÖL (8 ilçe)
('Adaklı', 'adakli', (SELECT id FROM cities WHERE slug = 'bingol')),
('Genç', 'genc', (SELECT id FROM cities WHERE slug = 'bingol')),
('Karlıova', 'karliova', (SELECT id FROM cities WHERE slug = 'bingol')),
('Kiğı', 'kigi', (SELECT id FROM cities WHERE slug = 'bingol')),
('Merkez', 'merkez-bingol', (SELECT id FROM cities WHERE slug = 'bingol')),
('Solhan', 'solhan', (SELECT id FROM cities WHERE slug = 'bingol')),
('Yayladere', 'yayladere', (SELECT id FROM cities WHERE slug = 'bingol')),
('Yedisu', 'yedisu', (SELECT id FROM cities WHERE slug = 'bingol')),

-- BİTLİS (7 ilçe)
('Adilcevaz', 'adilcevaz', (SELECT id FROM cities WHERE slug = 'bitlis')),
('Ahlat', 'ahlat', (SELECT id FROM cities WHERE slug = 'bitlis')),
('Güroymak', 'guroymak', (SELECT id FROM cities WHERE slug = 'bitlis')),
('Hizan', 'hizan', (SELECT id FROM cities WHERE slug = 'bitlis')),
('Merkez', 'merkez-bitlis', (SELECT id FROM cities WHERE slug = 'bitlis')),
('Mutki', 'mutki', (SELECT id FROM cities WHERE slug = 'bitlis')),
('Tatvan', 'tatvan', (SELECT id FROM cities WHERE slug = 'bitlis')),

-- BOLU (9 ilçe)
('Dörtdivan', 'dortdivan', (SELECT id FROM cities WHERE slug = 'bolu')),
('Gerede', 'gerede', (SELECT id FROM cities WHERE slug = 'bolu')),
('Göynük', 'goynuk', (SELECT id FROM cities WHERE slug = 'bolu')),
('Kıbrıscık', 'kibriscik', (SELECT id FROM cities WHERE slug = 'bolu')),
('Mengen', 'mengen', (SELECT id FROM cities WHERE slug = 'bolu')),
('Merkez', 'merkez-bolu', (SELECT id FROM cities WHERE slug = 'bolu')),
('Mudurnu', 'mudurnu', (SELECT id FROM cities WHERE slug = 'bolu')),
('Seben', 'seben', (SELECT id FROM cities WHERE slug = 'bolu')),
('Yeniçağa', 'yenicaga', (SELECT id FROM cities WHERE slug = 'bolu')),

-- BURDUR (11 ilçe)
('Ağlasun', 'aglasun', (SELECT id FROM cities WHERE slug = 'burdur')),
('Altınyayla', 'altinyayla-burdur', (SELECT id FROM cities WHERE slug = 'burdur')),
('Bucak', 'bucak', (SELECT id FROM cities WHERE slug = 'burdur')),
('Çavdır', 'cavdir', (SELECT id FROM cities WHERE slug = 'burdur')),
('Çeltikçi', 'celtikci', (SELECT id FROM cities WHERE slug = 'burdur')),
('Gölhisar', 'golhisar', (SELECT id FROM cities WHERE slug = 'burdur')),
('Karamanlı', 'karamanli', (SELECT id FROM cities WHERE slug = 'burdur')),
('Kemer', 'kemer-burdur', (SELECT id FROM cities WHERE slug = 'burdur')),
('Merkez', 'merkez-burdur', (SELECT id FROM cities WHERE slug = 'burdur')),
('Tefenni', 'tefenni', (SELECT id FROM cities WHERE slug = 'burdur')),
('Yeşilova', 'yesilova', (SELECT id FROM cities WHERE slug = 'burdur')),

-- BURSA (17 ilçe)
('Büyükorhan', 'buyukorhan', (SELECT id FROM cities WHERE slug = 'bursa')),
('Gemlik', 'gemlik', (SELECT id FROM cities WHERE slug = 'bursa')),
('Gürsu', 'gursu', (SELECT id FROM cities WHERE slug = 'bursa')),
('Harmancık', 'harmancik', (SELECT id FROM cities WHERE slug = 'bursa')),
('İnegöl', 'inegol', (SELECT id FROM cities WHERE slug = 'bursa')),
('İznik', 'iznik', (SELECT id FROM cities WHERE slug = 'bursa')),
('Karacabey', 'karacabey', (SELECT id FROM cities WHERE slug = 'bursa')),
('Keles', 'keles', (SELECT id FROM cities WHERE slug = 'bursa')),
('Kestel', 'kestel', (SELECT id FROM cities WHERE slug = 'bursa')),
('Mudanya', 'mudanya', (SELECT id FROM cities WHERE slug = 'bursa')),
('Mustafakemalpaşa', 'mustafakemalpasa', (SELECT id FROM cities WHERE slug = 'bursa')),
('Nilüfer', 'nilufer', (SELECT id FROM cities WHERE slug = 'bursa')),
('Orhaneli', 'orhaneli', (SELECT id FROM cities WHERE slug = 'bursa')),
('Orhangazi', 'orhangazi', (SELECT id FROM cities WHERE slug = 'bursa')),
('Osmangazi', 'osmangazi', (SELECT id FROM cities WHERE slug = 'bursa')),
('Yenişehir', 'yenisehir-bursa', (SELECT id FROM cities WHERE slug = 'bursa')),
('Yıldırım', 'yildirim', (SELECT id FROM cities WHERE slug = 'bursa')),

-- ÇANAKKALE (12 ilçe)
('Ayvacık', 'ayvacik-canakkale', (SELECT id FROM cities WHERE slug = 'canakkale')),
('Bayramiç', 'bayramic', (SELECT id FROM cities WHERE slug = 'canakkale')),
('Biga', 'biga', (SELECT id FROM cities WHERE slug = 'canakkale')),
('Bozcaada', 'bozcaada', (SELECT id FROM cities WHERE slug = 'canakkale')),
('Çan', 'can', (SELECT id FROM cities WHERE slug = 'canakkale')),
('Eceabat', 'eceabat', (SELECT id FROM cities WHERE slug = 'canakkale')),
('Ezine', 'ezine', (SELECT id FROM cities WHERE slug = 'canakkale')),
('Gelibolu', 'gelibolu', (SELECT id FROM cities WHERE slug = 'canakkale')),
('Gökçeada', 'gokceada', (SELECT id FROM cities WHERE slug = 'canakkale')),
('Lapseki', 'lapseki', (SELECT id FROM cities WHERE slug = 'canakkale')),
('Merkez', 'merkez-canakkale', (SELECT id FROM cities WHERE slug = 'canakkale')),
('Yenice', 'yenice-canakkale', (SELECT id FROM cities WHERE slug = 'canakkale')),

-- ÇANKIRI (12 ilçe)
('Atkaracalar', 'atkaracalar', (SELECT id FROM cities WHERE slug = 'cankiri')),
('Bayramören', 'bayramoren', (SELECT id FROM cities WHERE slug = 'cankiri')),
('Çerkeş', 'cerkes', (SELECT id FROM cities WHERE slug = 'cankiri')),
('Eldivan', 'eldivan', (SELECT id FROM cities WHERE slug = 'cankiri')),
('Ilgaz', 'ilgaz', (SELECT id FROM cities WHERE slug = 'cankiri')),
('Kızılırmak', 'kizilirmak', (SELECT id FROM cities WHERE slug = 'cankiri')),
('Korgun', 'korgun', (SELECT id FROM cities WHERE slug = 'cankiri')),
('Kurşunlu', 'kursunlu', (SELECT id FROM cities WHERE slug = 'cankiri')),
('Merkez', 'merkez-cankiri', (SELECT id FROM cities WHERE slug = 'cankiri')),
('Orta', 'orta', (SELECT id FROM cities WHERE slug = 'cankiri')),
('Şabanözü', 'sabanozu', (SELECT id FROM cities WHERE slug = 'cankiri')),
('Yapraklı', 'yaprakli', (SELECT id FROM cities WHERE slug = 'cankiri')),

-- ÇORUM (14 ilçe)
('Alaca', 'alaca', (SELECT id FROM cities WHERE slug = 'corum')),
('Bayat', 'bayat-corum', (SELECT id FROM cities WHERE slug = 'corum')),
('Boğazkale', 'bogazkale', (SELECT id FROM cities WHERE slug = 'corum')),
('Dodurga', 'dodurga', (SELECT id FROM cities WHERE slug = 'corum')),
('İskilip', 'iskilip', (SELECT id FROM cities WHERE slug = 'corum')),
('Kargı', 'kargi', (SELECT id FROM cities WHERE slug = 'corum')),
('Laçin', 'lacin', (SELECT id FROM cities WHERE slug = 'corum')),
('Mecitözü', 'mecitozu', (SELECT id FROM cities WHERE slug = 'corum')),
('Merkez', 'merkez-corum', (SELECT id FROM cities WHERE slug = 'corum')),
('Oğuzlar', 'oguzlar', (SELECT id FROM cities WHERE slug = 'corum')),
('Ortaköy', 'ortakoy-corum', (SELECT id FROM cities WHERE slug = 'corum')),
('Osmancık', 'osmancik', (SELECT id FROM cities WHERE slug = 'corum')),
('Sungurlu', 'sungurlu', (SELECT id FROM cities WHERE slug = 'corum')),
('Uğurludağ', 'ugurludag', (SELECT id FROM cities WHERE slug = 'corum')),

-- DENİZLİ (19 ilçe)
('Acıpayam', 'acipayam', (SELECT id FROM cities WHERE slug = 'denizli')),
('Babadağ', 'babadag', (SELECT id FROM cities WHERE slug = 'denizli')),
('Baklan', 'baklan', (SELECT id FROM cities WHERE slug = 'denizli')),
('Bekilli', 'bekilli', (SELECT id FROM cities WHERE slug = 'denizli')),
('Beyağaç', 'beyagac', (SELECT id FROM cities WHERE slug = 'denizli')),
('Bozkurt', 'bozkurt-denizli', (SELECT id FROM cities WHERE slug = 'denizli')),
('Buldan', 'buldan', (SELECT id FROM cities WHERE slug = 'denizli')),
('Çal', 'cal', (SELECT id FROM cities WHERE slug = 'denizli')),
('Çameli', 'cameli', (SELECT id FROM cities WHERE slug = 'denizli')),
('Çardak', 'cardak', (SELECT id FROM cities WHERE slug = 'denizli')),
('Çivril', 'civril', (SELECT id FROM cities WHERE slug = 'denizli')),
('Güney', 'guney', (SELECT id FROM cities WHERE slug = 'denizli')),
('Honaz', 'honaz', (SELECT id FROM cities WHERE slug = 'denizli')),
('Kale', 'kale-denizli', (SELECT id FROM cities WHERE slug = 'denizli')),
('Merkezefendi', 'merkezefendi', (SELECT id FROM cities WHERE slug = 'denizli')),
('Pamukkale', 'pamukkale', (SELECT id FROM cities WHERE slug = 'denizli')),
('Sarayköy', 'saraykoy', (SELECT id FROM cities WHERE slug = 'denizli')),
('Serinhisar', 'serinhisar', (SELECT id FROM cities WHERE slug = 'denizli')),
('Tavas', 'tavas', (SELECT id FROM cities WHERE slug = 'denizli')),

-- DİYARBAKIR (17 ilçe)
('Bağlar', 'baglar', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Bismil', 'bismil', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Çermik', 'cermik', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Çınar', 'cinar', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Çüngüş', 'cungus', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Dicle', 'dicle', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Eğil', 'egil', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Ergani', 'ergani', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Hani', 'hani', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Hazro', 'hazro', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Kayapınar', 'kayapinar', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Kocaköy', 'kocakoy', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Kulp', 'kulp', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Lice', 'lice', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Silvan', 'silvan', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Sur', 'sur', (SELECT id FROM cities WHERE slug = 'diyarbakir')),
('Yenişehir', 'yenisehir-diyarbakir', (SELECT id FROM cities WHERE slug = 'diyarbakir')),

-- DÜZCE (8 ilçe)
('Akçakoca', 'akcakoca', (SELECT id FROM cities WHERE slug = 'duzce')),
('Cumayeri', 'cumayeri', (SELECT id FROM cities WHERE slug = 'duzce')),
('Çilimli', 'cilimli', (SELECT id FROM cities WHERE slug = 'duzce')),
('Gölyaka', 'golyaka', (SELECT id FROM cities WHERE slug = 'duzce')),
('Gümüşova', 'gumusova', (SELECT id FROM cities WHERE slug = 'duzce')),
('Kaynaşlı', 'kaynasli', (SELECT id FROM cities WHERE slug = 'duzce')),
('Merkez', 'merkez-duzce', (SELECT id FROM cities WHERE slug = 'duzce')),
('Yığılca', 'yigilca', (SELECT id FROM cities WHERE slug = 'duzce')),

-- EDİRNE (9 ilçe)
('Enez', 'enez', (SELECT id FROM cities WHERE slug = 'edirne')),
('Havsa', 'havsa', (SELECT id FROM cities WHERE slug = 'edirne')),
('İpsala', 'ipsala', (SELECT id FROM cities WHERE slug = 'edirne')),
('Keşan', 'kesan', (SELECT id FROM cities WHERE slug = 'edirne')),
('Lalapaşa', 'lalapasa', (SELECT id FROM cities WHERE slug = 'edirne')),
('Meriç', 'meric', (SELECT id FROM cities WHERE slug = 'edirne')),
('Merkez', 'merkez-edirne', (SELECT id FROM cities WHERE slug = 'edirne')),
('Süloğlu', 'suloglu', (SELECT id FROM cities WHERE slug = 'edirne')),
('Uzunköprü', 'uzunkopru', (SELECT id FROM cities WHERE slug = 'edirne')),

-- ELAZIĞ (11 ilçe)
('Ağın', 'agin', (SELECT id FROM cities WHERE slug = 'elazig')),
('Alacakaya', 'alacakaya', (SELECT id FROM cities WHERE slug = 'elazig')),
('Arıcak', 'aricak', (SELECT id FROM cities WHERE slug = 'elazig')),
('Baskil', 'baskil', (SELECT id FROM cities WHERE slug = 'elazig')),
('Karakoçan', 'karakocan', (SELECT id FROM cities WHERE slug = 'elazig')),
('Keban', 'keban', (SELECT id FROM cities WHERE slug = 'elazig')),
('Kovancılar', 'kovancilar', (SELECT id FROM cities WHERE slug = 'elazig')),
('Maden', 'maden', (SELECT id FROM cities WHERE slug = 'elazig')),
('Merkez', 'merkez-elazig', (SELECT id FROM cities WHERE slug = 'elazig')),
('Palu', 'palu', (SELECT id FROM cities WHERE slug = 'elazig')),
('Sivrice', 'sivrice', (SELECT id FROM cities WHERE slug = 'elazig')),

-- ERZİNCAN (9 ilçe)
('Çayırlı', 'cayirli', (SELECT id FROM cities WHERE slug = 'erzincan')),
('İliç', 'ilic', (SELECT id FROM cities WHERE slug = 'erzincan')),
('Kemah', 'kemah', (SELECT id FROM cities WHERE slug = 'erzincan')),
('Kemaliye', 'kemaliye', (SELECT id FROM cities WHERE slug = 'erzincan')),
('Merkez', 'merkez-erzincan', (SELECT id FROM cities WHERE slug = 'erzincan')),
('Otlukbeli', 'otlukbeli', (SELECT id FROM cities WHERE slug = 'erzincan')),
('Refahiye', 'refahiye', (SELECT id FROM cities WHERE slug = 'erzincan')),
('Tercan', 'tercan', (SELECT id FROM cities WHERE slug = 'erzincan')),
('Üzümlü', 'uzumlu', (SELECT id FROM cities WHERE slug = 'erzincan')),

-- ERZURUM (20 ilçe)
('Aşkale', 'askale', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Aziziye', 'aziziye', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Çat', 'cat', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Hınıs', 'hinis', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Horasan', 'horasan', (SELECT id FROM cities WHERE slug = 'erzurum')),
('İspir', 'ispir', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Karaçoban', 'karacoban', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Karayazı', 'karayazi', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Köprüköy', 'koprukoy', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Narman', 'narman', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Oltu', 'oltu', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Olur', 'olur', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Palandöken', 'palandoken', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Pasinler', 'pasinler', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Pazaryolu', 'pazaryolu', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Şenkaya', 'senkaya', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Tekman', 'tekman', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Tortum', 'tortum', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Uzundere', 'uzundere', (SELECT id FROM cities WHERE slug = 'erzurum')),
('Yakutiye', 'yakutiye', (SELECT id FROM cities WHERE slug = 'erzurum')),

-- ESKİŞEHİR (14 ilçe)
('Alpu', 'alpu', (SELECT id FROM cities WHERE slug = 'eskisehir')),
('Beylikova', 'beylikova', (SELECT id FROM cities WHERE slug = 'eskisehir')),
('Çifteler', 'cifteler', (SELECT id FROM cities WHERE slug = 'eskisehir')),
('Günyüzü', 'gunyuzu', (SELECT id FROM cities WHERE slug = 'eskisehir')),
('Han', 'han', (SELECT id FROM cities WHERE slug = 'eskisehir')),
('İnönü', 'inonu', (SELECT id FROM cities WHERE slug = 'eskisehir')),
('Mahmudiye', 'mahmudiye', (SELECT id FROM cities WHERE slug = 'eskisehir')),
('Mihalgazi', 'mihalgazi', (SELECT id FROM cities WHERE slug = 'eskisehir')),
('Mihalıççık', 'mihaliccik', (SELECT id FROM cities WHERE slug = 'eskisehir')),
('Odunpazarı', 'odunpazari', (SELECT id FROM cities WHERE slug = 'eskisehir')),
('Sarıcakaya', 'saricakaya', (SELECT id FROM cities WHERE slug = 'eskisehir')),
('Seyitgazi', 'seyitgazi', (SELECT id FROM cities WHERE slug = 'eskisehir')),
('Sivrihisar', 'sivrihisar', (SELECT id FROM cities WHERE slug = 'eskisehir')),
('Tepebaşı', 'tepebasi', (SELECT id FROM cities WHERE slug = 'eskisehir')),

-- GAZİANTEP (9 ilçe)
('Araban', 'araban', (SELECT id FROM cities WHERE slug = 'gaziantep')),
('İslahiye', 'islahiye', (SELECT id FROM cities WHERE slug = 'gaziantep')),
('Karkamış', 'karkamis', (SELECT id FROM cities WHERE slug = 'gaziantep')),
('Nizip', 'nizip', (SELECT id FROM cities WHERE slug = 'gaziantep')),
('Nurdağı', 'nurdagi', (SELECT id FROM cities WHERE slug = 'gaziantep')),
('Oğuzeli', 'oguzeli', (SELECT id FROM cities WHERE slug = 'gaziantep')),
('Şahinbey', 'sahinbey', (SELECT id FROM cities WHERE slug = 'gaziantep')),
('Şehitkamil', 'sehitkamil', (SELECT id FROM cities WHERE slug = 'gaziantep')),
('Yavuzeli', 'yavuzeli', (SELECT id FROM cities WHERE slug = 'gaziantep')),

-- GİRESUN (16 ilçe)
('Alucra', 'alucra', (SELECT id FROM cities WHERE slug = 'giresun')),
('Bulancak', 'bulancak', (SELECT id FROM cities WHERE slug = 'giresun')),
('Çamoluk', 'camoluk', (SELECT id FROM cities WHERE slug = 'giresun')),
('Çanakçı', 'canakci', (SELECT id FROM cities WHERE slug = 'giresun')),
('Dereli', 'dereli', (SELECT id FROM cities WHERE slug = 'giresun')),
('Doğankent', 'dogankent', (SELECT id FROM cities WHERE slug = 'giresun')),
('Espiye', 'espiye', (SELECT id FROM cities WHERE slug = 'giresun')),
('Eynesil', 'eynesil', (SELECT id FROM cities WHERE slug = 'giresun')),
('Görele', 'gorele', (SELECT id FROM cities WHERE slug = 'giresun')),
('Güce', 'guce', (SELECT id FROM cities WHERE slug = 'giresun')),
('Keşap', 'kesap', (SELECT id FROM cities WHERE slug = 'giresun')),
('Merkez', 'merkez-giresun', (SELECT id FROM cities WHERE slug = 'giresun')),
('Piraziz', 'piraziz', (SELECT id FROM cities WHERE slug = 'giresun')),
('Şebinkarahisar', 'sebinkarahisar', (SELECT id FROM cities WHERE slug = 'giresun')),
('Tirebolu', 'tirebolu', (SELECT id FROM cities WHERE slug = 'giresun')),
('Yağlıdere', 'yaglidere', (SELECT id FROM cities WHERE slug = 'giresun')),

-- GÜMÜŞHANE (6 ilçe)
('Kelkit', 'kelkit', (SELECT id FROM cities WHERE slug = 'gumushane')),
('Köse', 'kose', (SELECT id FROM cities WHERE slug = 'gumushane')),
('Kürtün', 'kurtun', (SELECT id FROM cities WHERE slug = 'gumushane')),
('Merkez', 'merkez-gumushane', (SELECT id FROM cities WHERE slug = 'gumushane')),
('Şiran', 'siran', (SELECT id FROM cities WHERE slug = 'gumushane')),
('Torul', 'torul', (SELECT id FROM cities WHERE slug = 'gumushane')),

-- HAKKARİ (4 ilçe)
('Çukurca', 'cukurca', (SELECT id FROM cities WHERE slug = 'hakkari')),
('Merkez', 'merkez-hakkari', (SELECT id FROM cities WHERE slug = 'hakkari')),
('Şemdinli', 'semdinli', (SELECT id FROM cities WHERE slug = 'hakkari')),
('Yüksekova', 'yuksekova', (SELECT id FROM cities WHERE slug = 'hakkari')),

-- HATAY (15 ilçe)
('Altınözü', 'altinozu', (SELECT id FROM cities WHERE slug = 'hatay')),
('Antakya', 'antakya', (SELECT id FROM cities WHERE slug = 'hatay')),
('Arsuz', 'arsuz', (SELECT id FROM cities WHERE slug = 'hatay')),
('Belen', 'belen', (SELECT id FROM cities WHERE slug = 'hatay')),
('Defne', 'defne', (SELECT id FROM cities WHERE slug = 'hatay')),
('Dörtyol', 'dortyol', (SELECT id FROM cities WHERE slug = 'hatay')),
('Erzin', 'erzin', (SELECT id FROM cities WHERE slug = 'hatay')),
('Hassa', 'hassa', (SELECT id FROM cities WHERE slug = 'hatay')),
('İskenderun', 'iskenderun', (SELECT id FROM cities WHERE slug = 'hatay')),
('Kırıkhan', 'kirikhan', (SELECT id FROM cities WHERE slug = 'hatay')),
('Kumlu', 'kumlu', (SELECT id FROM cities WHERE slug = 'hatay')),
('Payas', 'payas', (SELECT id FROM cities WHERE slug = 'hatay')),
('Reyhanlı', 'reyhanli', (SELECT id FROM cities WHERE slug = 'hatay')),
('Samandağ', 'samandag', (SELECT id FROM cities WHERE slug = 'hatay')),
('Yayladağı', 'yayladagi', (SELECT id FROM cities WHERE slug = 'hatay')),

-- IĞDIR (4 ilçe)
('Aralık', 'aralik', (SELECT id FROM cities WHERE slug = 'igdir')),
('Karakoyunlu', 'karakoyunlu', (SELECT id FROM cities WHERE slug = 'igdir')),
('Merkez', 'merkez-igdir', (SELECT id FROM cities WHERE slug = 'igdir')),
('Tuzluca', 'tuzluca', (SELECT id FROM cities WHERE slug = 'igdir')),

-- ISPARTA (13 ilçe)
('Aksu', 'aksu-isparta', (SELECT id FROM cities WHERE slug = 'isparta')),
('Atabey', 'atabey', (SELECT id FROM cities WHERE slug = 'isparta')),
('Eğirdir', 'egirdir', (SELECT id FROM cities WHERE slug = 'isparta')),
('Gelendost', 'gelendost', (SELECT id FROM cities WHERE slug = 'isparta')),
('Gönen', 'gonen-isparta', (SELECT id FROM cities WHERE slug = 'isparta')),
('Keçiborlu', 'keciborlu', (SELECT id FROM cities WHERE slug = 'isparta')),
('Merkez', 'merkez-isparta', (SELECT id FROM cities WHERE slug = 'isparta')),
('Senirkent', 'senirkent', (SELECT id FROM cities WHERE slug = 'isparta')),
('Sütçüler', 'sutculer', (SELECT id FROM cities WHERE slug = 'isparta')),
('Şarkikaraağaç', 'sarkikaraagac', (SELECT id FROM cities WHERE slug = 'isparta')),
('Uluborlu', 'uluborlu', (SELECT id FROM cities WHERE slug = 'isparta')),
('Yalvaç', 'yalvac', (SELECT id FROM cities WHERE slug = 'isparta')),
('Yenişarbademli', 'yenisarbademli', (SELECT id FROM cities WHERE slug = 'isparta')),

-- İSTANBUL (39 ilçe)
('Adalar', 'adalar', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Arnavutköy', 'arnavutkoy', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Ataşehir', 'atasehir', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Avcılar', 'avcilar', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Bağcılar', 'bagcilar', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Bahçelievler', 'bahcelievler', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Bakırköy', 'bakirkoy', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Başakşehir', 'basaksehir', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Bayrampaşa', 'bayrampasa', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Beşiktaş', 'besiktas', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Beykoz', 'beykoz', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Beylikdüzü', 'beylikduzu', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Beyoğlu', 'beyoglu', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Büyükçekmece', 'buyukcekmece', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Çatalca', 'catalca', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Çekmeköy', 'cekmekoy', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Esenler', 'esenler', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Esenyurt', 'esenyurt', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Eyüpsultan', 'eyupsultan', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Fatih', 'fatih', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Gaziosmanpaşa', 'gaziosmanpasa', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Güngören', 'gungoren', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Kadıköy', 'kadikoy', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Kağıthane', 'kagithane', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Kartal', 'kartal', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Küçükçekmece', 'kucukcekmece', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Maltepe', 'maltepe', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Pendik', 'pendik', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Sancaktepe', 'sancaktepe', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Sarıyer', 'sariyer', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Şile', 'sile', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Şişli', 'sisli', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Silivri', 'silivri', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Sultanbeyli', 'sultanbeyli', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Sultangazi', 'sultangazi', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Tuzla', 'tuzla', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Ümraniye', 'umraniye', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Üsküdar', 'uskudar', (SELECT id FROM cities WHERE slug = 'istanbul')),
('Zeytinburnu', 'zeytinburnu', (SELECT id FROM cities WHERE slug = 'istanbul')),

-- İZMİR (30 ilçe)
('Aliağa', 'aliaga', (SELECT id FROM cities WHERE slug = 'izmir')),
('Balçova', 'balcova', (SELECT id FROM cities WHERE slug = 'izmir')),
('Bayındır', 'bayindir', (SELECT id FROM cities WHERE slug = 'izmir')),
('Bayraklı', 'bayrakli', (SELECT id FROM cities WHERE slug = 'izmir')),
('Bergama', 'bergama', (SELECT id FROM cities WHERE slug = 'izmir')),
('Beydağ', 'beydag', (SELECT id FROM cities WHERE slug = 'izmir')),
('Bornova', 'bornova', (SELECT id FROM cities WHERE slug = 'izmir')),
('Buca', 'buca', (SELECT id FROM cities WHERE slug = 'izmir')),
('Çeşme', 'cesme', (SELECT id FROM cities WHERE slug = 'izmir')),
('Çiğli', 'cigli', (SELECT id FROM cities WHERE slug = 'izmir')),
('Dikili', 'dikili', (SELECT id FROM cities WHERE slug = 'izmir')),
('Foça', 'foca', (SELECT id FROM cities WHERE slug = 'izmir')),
('Gaziemir', 'gaziemir', (SELECT id FROM cities WHERE slug = 'izmir')),
('Güzelbahçe', 'guzelbahce', (SELECT id FROM cities WHERE slug = 'izmir')),
('Karabağlar', 'karabaglar', (SELECT id FROM cities WHERE slug = 'izmir')),
('Karaburun', 'karaburun', (SELECT id FROM cities WHERE slug = 'izmir')),
('Karşıyaka', 'karsiyaka', (SELECT id FROM cities WHERE slug = 'izmir')),
('Kemalpaşa', 'kemalpasa-izmir', (SELECT id FROM cities WHERE slug = 'izmir')),
('Kınık', 'kinik', (SELECT id FROM cities WHERE slug = 'izmir')),
('Kiraz', 'kiraz', (SELECT id FROM cities WHERE slug = 'izmir')),
('Konak', 'konak', (SELECT id FROM cities WHERE slug = 'izmir')),
('Menderes', 'menderes', (SELECT id FROM cities WHERE slug = 'izmir')),
('Menemen', 'menemen', (SELECT id FROM cities WHERE slug = 'izmir')),
('Narlıdere', 'narlidere', (SELECT id FROM cities WHERE slug = 'izmir')),
('Ödemiş', 'odemis', (SELECT id FROM cities WHERE slug = 'izmir')),
('Seferihisar', 'seferihisar', (SELECT id FROM cities WHERE slug = 'izmir')),
('Selçuk', 'selcuk', (SELECT id FROM cities WHERE slug = 'izmir')),
('Tire', 'tire', (SELECT id FROM cities WHERE slug = 'izmir')),
('Torbalı', 'torbali', (SELECT id FROM cities WHERE slug = 'izmir')),
('Urla', 'urla', (SELECT id FROM cities WHERE slug = 'izmir')),

-- KAHRAMANMARAŞ (11 ilçe)
('Afşin', 'afsin', (SELECT id FROM cities WHERE slug = 'kahramanmaras')),
('Andırın', 'andirin', (SELECT id FROM cities WHERE slug = 'kahramanmaras')),
('Çağlayancerit', 'caglayancerit', (SELECT id FROM cities WHERE slug = 'kahramanmaras')),
('Dulkadiroğlu', 'dulkadiroglu', (SELECT id FROM cities WHERE slug = 'kahramanmaras')),
('Ekinözü', 'ekinozu', (SELECT id FROM cities WHERE slug = 'kahramanmaras')),
('Elbistan', 'elbistan', (SELECT id FROM cities WHERE slug = 'kahramanmaras')),
('Göksun', 'goksun', (SELECT id FROM cities WHERE slug = 'kahramanmaras')),
('Nurhak', 'nurhak', (SELECT id FROM cities WHERE slug = 'kahramanmaras')),
('Onikişubat', 'onikisubat', (SELECT id FROM cities WHERE slug = 'kahramanmaras')),
('Pazarcık', 'pazarcik', (SELECT id FROM cities WHERE slug = 'kahramanmaras')),
('Türkoğlu', 'turkoglu', (SELECT id FROM cities WHERE slug = 'kahramanmaras')),

-- KARABÜK (6 ilçe)
('Eflani', 'eflani', (SELECT id FROM cities WHERE slug = 'karabuk')),
('Eskipazar', 'eskipazar', (SELECT id FROM cities WHERE slug = 'karabuk')),
('Merkez', 'merkez-karabuk', (SELECT id FROM cities WHERE slug = 'karabuk')),
('Ovacık', 'ovacik-karabuk', (SELECT id FROM cities WHERE slug = 'karabuk')),
('Safranbolu', 'safranbolu', (SELECT id FROM cities WHERE slug = 'karabuk')),
('Yenice', 'yenice-karabuk', (SELECT id FROM cities WHERE slug = 'karabuk')),

-- KARAMAN (6 ilçe)
('Ayrancı', 'ayranci', (SELECT id FROM cities WHERE slug = 'karaman')),
('Başyayla', 'basyayla', (SELECT id FROM cities WHERE slug = 'karaman')),
('Ermenek', 'ermenek', (SELECT id FROM cities WHERE slug = 'karaman')),
('Kazımkarabekir', 'kazimkarabekir', (SELECT id FROM cities WHERE slug = 'karaman')),
('Merkez', 'merkez-karaman', (SELECT id FROM cities WHERE slug = 'karaman')),
('Sarıveliler', 'sariveliler', (SELECT id FROM cities WHERE slug = 'karaman')),

-- KARS (8 ilçe)
('Akyaka', 'akyaka', (SELECT id FROM cities WHERE slug = 'kars')),
('Arpaçay', 'arpacay', (SELECT id FROM cities WHERE slug = 'kars')),
('Digor', 'digor', (SELECT id FROM cities WHERE slug = 'kars')),
('Kağızman', 'kagizman', (SELECT id FROM cities WHERE slug = 'kars')),
('Merkez', 'merkez-kars', (SELECT id FROM cities WHERE slug = 'kars')),
('Sarıkamış', 'sarikamis', (SELECT id FROM cities WHERE slug = 'kars')),
('Selim', 'selim', (SELECT id FROM cities WHERE slug = 'kars')),
('Susuz', 'susuz', (SELECT id FROM cities WHERE slug = 'kars')),

-- KASTAMONU (20 ilçe)
('Abana', 'abana', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Ağlı', 'agli', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Araç', 'arac', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Azdavay', 'azdavay', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Bozkurt', 'bozkurt-kastamonu', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Cide', 'cide', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Çatalzeytin', 'catalzeytin', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Daday', 'daday', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Devrekani', 'devrekani', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Doğanyurt', 'doganyurt', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Hanönü', 'hanonu', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('İhsangazi', 'ihsangazi', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('İnebolu', 'inebolu', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Küre', 'kure', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Merkez', 'merkez-kastamonu', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Pınarbaşı', 'pinarbasi-kastamonu', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Seydiler', 'seydiler', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Şenpazar', 'senpazar', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Taşköprü', 'taskopru', (SELECT id FROM cities WHERE slug = 'kastamonu')),
('Tosya', 'tosya', (SELECT id FROM cities WHERE slug = 'kastamonu')),

-- KAYSERİ (16 ilçe)
('Akkışla', 'akkisla', (SELECT id FROM cities WHERE slug = 'kayseri')),
('Bünyan', 'bunyan', (SELECT id FROM cities WHERE slug = 'kayseri')),
('Develi', 'develi', (SELECT id FROM cities WHERE slug = 'kayseri')),
('Felahiye', 'felahiye', (SELECT id FROM cities WHERE slug = 'kayseri')),
('Hacılar', 'hacilar', (SELECT id FROM cities WHERE slug = 'kayseri')),
('İncesu', 'incesu', (SELECT id FROM cities WHERE slug = 'kayseri')),
('Kocasinan', 'kocasinan', (SELECT id FROM cities WHERE slug = 'kayseri')),
('Melikgazi', 'melikgazi', (SELECT id FROM cities WHERE slug = 'kayseri')),
('Özvatan', 'ozvatan', (SELECT id FROM cities WHERE slug = 'kayseri')),
('Pınarbaşı', 'pinarbasi-kayseri', (SELECT id FROM cities WHERE slug = 'kayseri')),
('Sarıoğlan', 'sarioglan', (SELECT id FROM cities WHERE slug = 'kayseri')),
('Sarız', 'sariz', (SELECT id FROM cities WHERE slug = 'kayseri')),
('Talas', 'talas', (SELECT id FROM cities WHERE slug = 'kayseri')),
('Tomarza', 'tomarza', (SELECT id FROM cities WHERE slug = 'kayseri')),
('Yahyalı', 'yahyali', (SELECT id FROM cities WHERE slug = 'kayseri')),
('Yeşilhisar', 'yesilhisar', (SELECT id FROM cities WHERE slug = 'kayseri')),

-- KİLİS (4 ilçe)
('Elbeyli', 'elbeyli', (SELECT id FROM cities WHERE slug = 'kilis')),
('Merkez', 'merkez-kilis', (SELECT id FROM cities WHERE slug = 'kilis')),
('Musabeyli', 'musabeyli', (SELECT id FROM cities WHERE slug = 'kilis')),
('Polateli', 'polateli', (SELECT id FROM cities WHERE slug = 'kilis')),

-- KIRIKKALE (9 ilçe)
('Bahşılı', 'bahsili', (SELECT id FROM cities WHERE slug = 'kirikkale')),
('Balışeyh', 'baliseyh', (SELECT id FROM cities WHERE slug = 'kirikkale')),
('Çelebi', 'celebi', (SELECT id FROM cities WHERE slug = 'kirikkale')),
('Delice', 'delice', (SELECT id FROM cities WHERE slug = 'kirikkale')),
('Karakeçili', 'karakecili', (SELECT id FROM cities WHERE slug = 'kirikkale')),
('Keskin', 'keskin', (SELECT id FROM cities WHERE slug = 'kirikkale')),
('Merkez', 'merkez-kirikkale', (SELECT id FROM cities WHERE slug = 'kirikkale')),
('Sulakyurt', 'sulakyurt', (SELECT id FROM cities WHERE slug = 'kirikkale')),
('Yahşihan', 'yahsihan', (SELECT id FROM cities WHERE slug = 'kirikkale')),

-- KIRKLARELİ (8 ilçe)
('Babaeski', 'babaeski', (SELECT id FROM cities WHERE slug = 'kirklareli')),
('Demirköy', 'demirkoy', (SELECT id FROM cities WHERE slug = 'kirklareli')),
('Kofçaz', 'kofcaz', (SELECT id FROM cities WHERE slug = 'kirklareli')),
('Lüleburgaz', 'luleburgaz', (SELECT id FROM cities WHERE slug = 'kirklareli')),
('Merkez', 'merkez-kirklareli', (SELECT id FROM cities WHERE slug = 'kirklareli')),
('Pehlivanköy', 'pehlivankoy', (SELECT id FROM cities WHERE slug = 'kirklareli')),
('Pınarhisar', 'pinarhisar', (SELECT id FROM cities WHERE slug = 'kirklareli')),
('Vize', 'vize', (SELECT id FROM cities WHERE slug = 'kirklareli')),

-- KIRŞEHİR (7 ilçe)
('Akçakent', 'akcakent', (SELECT id FROM cities WHERE slug = 'kirsehir')),
('Akpınar', 'akpinar', (SELECT id FROM cities WHERE slug = 'kirsehir')),
('Boztepe', 'boztepe', (SELECT id FROM cities WHERE slug = 'kirsehir')),
('Çiçekdağı', 'cicekdagi', (SELECT id FROM cities WHERE slug = 'kirsehir')),
('Kaman', 'kaman', (SELECT id FROM cities WHERE slug = 'kirsehir')),
('Merkez', 'merkez-kirsehir', (SELECT id FROM cities WHERE slug = 'kirsehir')),
('Mucur', 'mucur', (SELECT id FROM cities WHERE slug = 'kirsehir')),

-- KOCAELİ (12 ilçe)
('Başiskele', 'basiskele', (SELECT id FROM cities WHERE slug = 'kocaeli')),
('Çayırova', 'cayirova', (SELECT id FROM cities WHERE slug = 'kocaeli')),
('Darıca', 'darica', (SELECT id FROM cities WHERE slug = 'kocaeli')),
('Derince', 'derince', (SELECT id FROM cities WHERE slug = 'kocaeli')),
('Dilovası', 'dilovasi', (SELECT id FROM cities WHERE slug = 'kocaeli')),
('Gebze', 'gebze', (SELECT id FROM cities WHERE slug = 'kocaeli')),
('Gölcük', 'golcuk', (SELECT id FROM cities WHERE slug = 'kocaeli')),
('İzmit', 'izmit', (SELECT id FROM cities WHERE slug = 'kocaeli')),
('Kandıra', 'kandira', (SELECT id FROM cities WHERE slug = 'kocaeli')),
('Karamürsel', 'karamursel', (SELECT id FROM cities WHERE slug = 'kocaeli')),
('Kartepe', 'kartepe', (SELECT id FROM cities WHERE slug = 'kocaeli')),
('Körfez', 'korfez', (SELECT id FROM cities WHERE slug = 'kocaeli')),

-- KONYA (31 ilçe)
('Ahırlı', 'ahirli', (SELECT id FROM cities WHERE slug = 'konya')),
('Akören', 'akoren', (SELECT id FROM cities WHERE slug = 'konya')),
('Akşehir', 'aksehir', (SELECT id FROM cities WHERE slug = 'konya')),
('Altınekin', 'altinekin', (SELECT id FROM cities WHERE slug = 'konya')),
('Beyşehir', 'beysehir', (SELECT id FROM cities WHERE slug = 'konya')),
('Bozkır', 'bozkir', (SELECT id FROM cities WHERE slug = 'konya')),
('Cihanbeyli', 'cihanbeyli', (SELECT id FROM cities WHERE slug = 'konya')),
('Çeltik', 'celtik', (SELECT id FROM cities WHERE slug = 'konya')),
('Çumra', 'cumra', (SELECT id FROM cities WHERE slug = 'konya')),
('Derbent', 'derbent', (SELECT id FROM cities WHERE slug = 'konya')),
('Derebucak', 'derebucak', (SELECT id FROM cities WHERE slug = 'konya')),
('Doğanhisar', 'doganhisar', (SELECT id FROM cities WHERE slug = 'konya')),
('Emirgazi', 'emirgazi', (SELECT id FROM cities WHERE slug = 'konya')),
('Ereğli', 'eregli', (SELECT id FROM cities WHERE slug = 'konya')),
('Güneysınır', 'guneysinir', (SELECT id FROM cities WHERE slug = 'konya')),
('Hadım', 'hadim', (SELECT id FROM cities WHERE slug = 'konya')),
('Halkapınar', 'halkapinar', (SELECT id FROM cities WHERE slug = 'konya')),
('Hüyük', 'huyuk', (SELECT id FROM cities WHERE slug = 'konya')),
('Ilgın', 'ilgin', (SELECT id FROM cities WHERE slug = 'konya')),
('Kadınhanı', 'kadinhani', (SELECT id FROM cities WHERE slug = 'konya')),
('Karapınar', 'karapinar', (SELECT id FROM cities WHERE slug = 'konya')),
('Karatay', 'karatay', (SELECT id FROM cities WHERE slug = 'konya')),
('Kulu', 'kulu', (SELECT id FROM cities WHERE slug = 'konya')),
('Meram', 'meram', (SELECT id FROM cities WHERE slug = 'konya')),
('Sarayönü', 'sarayonu', (SELECT id FROM cities WHERE slug = 'konya')),
('Selçuklu', 'selcuklu', (SELECT id FROM cities WHERE slug = 'konya')),
('Seydişehir', 'seydisehir', (SELECT id FROM cities WHERE slug = 'konya')),
('Taşkent', 'taskent', (SELECT id FROM cities WHERE slug = 'konya')),
('Tuzlukçu', 'tuzlukcu', (SELECT id FROM cities WHERE slug = 'konya')),
('Yalıhüyük', 'yalihuyuk', (SELECT id FROM cities WHERE slug = 'konya')),
('Yunak', 'yunak', (SELECT id FROM cities WHERE slug = 'konya')),

-- KÜTAHYA (13 ilçe)
('Altıntaş', 'altintas', (SELECT id FROM cities WHERE slug = 'kutahya')),
('Aslanapa', 'aslanapa', (SELECT id FROM cities WHERE slug = 'kutahya')),
('Çavdarhisar', 'cavdarhisar', (SELECT id FROM cities WHERE slug = 'kutahya')),
('Domaniç', 'domanic', (SELECT id FROM cities WHERE slug = 'kutahya')),
('Dumlupınar', 'dumlupinar', (SELECT id FROM cities WHERE slug = 'kutahya')),
('Emet', 'emet', (SELECT id FROM cities WHERE slug = 'kutahya')),
('Gediz', 'gediz', (SELECT id FROM cities WHERE slug = 'kutahya')),
('Hisarcık', 'hisarcik', (SELECT id FROM cities WHERE slug = 'kutahya')),
('Merkez', 'merkez-kutahya', (SELECT id FROM cities WHERE slug = 'kutahya')),
('Pazarlar', 'pazarlar', (SELECT id FROM cities WHERE slug = 'kutahya')),
('Şaphane', 'saphane', (SELECT id FROM cities WHERE slug = 'kutahya')),
('Simav', 'simav', (SELECT id FROM cities WHERE slug = 'kutahya')),
('Tavşanlı', 'tavsanli', (SELECT id FROM cities WHERE slug = 'kutahya')),

-- MALATYA (13 ilçe)
('Akçadağ', 'akcadag', (SELECT id FROM cities WHERE slug = 'malatya')),
('Arapgir', 'arapgir', (SELECT id FROM cities WHERE slug = 'malatya')),
('Arguvan', 'arguvan', (SELECT id FROM cities WHERE slug = 'malatya')),
('Battalgazi', 'battalgazi', (SELECT id FROM cities WHERE slug = 'malatya')),
('Darende', 'darende', (SELECT id FROM cities WHERE slug = 'malatya')),
('Doğanşehir', 'dogansehir', (SELECT id FROM cities WHERE slug = 'malatya')),
('Doğanyol', 'doganyol', (SELECT id FROM cities WHERE slug = 'malatya')),
('Hekimhan', 'hekimhan', (SELECT id FROM cities WHERE slug = 'malatya')),
('Kale', 'kale-malatya', (SELECT id FROM cities WHERE slug = 'malatya')),
('Kuluncak', 'kuluncak', (SELECT id FROM cities WHERE slug = 'malatya')),
('Pütürge', 'puturge', (SELECT id FROM cities WHERE slug = 'malatya')),
('Yazıhan', 'yazihan', (SELECT id FROM cities WHERE slug = 'malatya')),
('Yeşilyurt', 'yesilyurt', (SELECT id FROM cities WHERE slug = 'malatya')),

-- MANİSA (17 ilçe)
('Ahmetli', 'ahmetli', (SELECT id FROM cities WHERE slug = 'manisa')),
('Akhisar', 'akhisar', (SELECT id FROM cities WHERE slug = 'manisa')),
('Alaşehir', 'alasehir', (SELECT id FROM cities WHERE slug = 'manisa')),
('Demirci', 'demirci', (SELECT id FROM cities WHERE slug = 'manisa')),
('Gölmarmara', 'golmarmara', (SELECT id FROM cities WHERE slug = 'manisa')),
('Gördes', 'gordes', (SELECT id FROM cities WHERE slug = 'manisa')),
('Kırkağaç', 'kirkagac', (SELECT id FROM cities WHERE slug = 'manisa')),
('Köprübaşı', 'koprubasi', (SELECT id FROM cities WHERE slug = 'manisa')),
('Kula', 'kula', (SELECT id FROM cities WHERE slug = 'manisa')),
('Salihli', 'salihli', (SELECT id FROM cities WHERE slug = 'manisa')),
('Sarıgöl', 'sarigol', (SELECT id FROM cities WHERE slug = 'manisa')),
('Saruhanlı', 'saruhanli', (SELECT id FROM cities WHERE slug = 'manisa')),
('Selendi', 'selendi', (SELECT id FROM cities WHERE slug = 'manisa')),
('Soma', 'soma', (SELECT id FROM cities WHERE slug = 'manisa')),
('Şehzadeler', 'sehzadeler', (SELECT id FROM cities WHERE slug = 'manisa')),
('Turgutlu', 'turgutlu', (SELECT id FROM cities WHERE slug = 'manisa')),
('Yunusemre', 'yunusemre', (SELECT id FROM cities WHERE slug = 'manisa')),

-- MARDİN (10 ilçe)
('Artuklu', 'artuklu', (SELECT id FROM cities WHERE slug = 'mardin')),
('Dargeçit', 'dargecit', (SELECT id FROM cities WHERE slug = 'mardin')),
('Derik', 'derik', (SELECT id FROM cities WHERE slug = 'mardin')),
('Kızıltepe', 'kiziltepe', (SELECT id FROM cities WHERE slug = 'mardin')),
('Mazıdağı', 'mazidagi', (SELECT id FROM cities WHERE slug = 'mardin')),
('Midyat', 'midyat', (SELECT id FROM cities WHERE slug = 'mardin')),
('Nusaybin', 'nusaybin', (SELECT id FROM cities WHERE slug = 'mardin')),
('Ömerli', 'omerli', (SELECT id FROM cities WHERE slug = 'mardin')),
('Savur', 'savur', (SELECT id FROM cities WHERE slug = 'mardin')),
('Yeşilli', 'yesilli', (SELECT id FROM cities WHERE slug = 'mardin')),

-- MERSİN (13 ilçe)
('Akdeniz', 'akdeniz', (SELECT id FROM cities WHERE slug = 'mersin')),
('Anamur', 'anamur', (SELECT id FROM cities WHERE slug = 'mersin')),
('Aydıncık', 'aydincik', (SELECT id FROM cities WHERE slug = 'mersin')),
('Bozyazı', 'bozyazi', (SELECT id FROM cities WHERE slug = 'mersin')),
('Çamlıyayla', 'camliyayla', (SELECT id FROM cities WHERE slug = 'mersin')),
('Erdemli', 'erdemli', (SELECT id FROM cities WHERE slug = 'mersin')),
('Gülnar', 'gulnar', (SELECT id FROM cities WHERE slug = 'mersin')),
('Mezitli', 'mezitli', (SELECT id FROM cities WHERE slug = 'mersin')),
('Mut', 'mut', (SELECT id FROM cities WHERE slug = 'mersin')),
('Silifke', 'silifke', (SELECT id FROM cities WHERE slug = 'mersin')),
('Tarsus', 'tarsus', (SELECT id FROM cities WHERE slug = 'mersin')),
('Toroslar', 'toroslar', (SELECT id FROM cities WHERE slug = 'mersin')),
('Yenişehir', 'yenisehir-mersin', (SELECT id FROM cities WHERE slug = 'mersin')),

-- MUĞLA (13 ilçe)
('Bodrum', 'bodrum', (SELECT id FROM cities WHERE slug = 'mugla')),
('Dalaman', 'dalaman', (SELECT id FROM cities WHERE slug = 'mugla')),
('Datça', 'datca', (SELECT id FROM cities WHERE slug = 'mugla')),
('Fethiye', 'fethiye', (SELECT id FROM cities WHERE slug = 'mugla')),
('Kavaklıdere', 'kavaklidere', (SELECT id FROM cities WHERE slug = 'mugla')),
('Köyceğiz', 'koycegiz', (SELECT id FROM cities WHERE slug = 'mugla')),
('Marmaris', 'marmaris', (SELECT id FROM cities WHERE slug = 'mugla')),
('Menteşe', 'mentese', (SELECT id FROM cities WHERE slug = 'mugla')),
('Milas', 'milas', (SELECT id FROM cities WHERE slug = 'mugla')),
('Ortaca', 'ortaca', (SELECT id FROM cities WHERE slug = 'mugla')),
('Seydikemer', 'seydikemer', (SELECT id FROM cities WHERE slug = 'mugla')),
('Ula', 'ula', (SELECT id FROM cities WHERE slug = 'mugla')),
('Yatağan', 'yatagan', (SELECT id FROM cities WHERE slug = 'mugla')),

-- MUŞ (6 ilçe)
('Bulanık', 'bulanik', (SELECT id FROM cities WHERE slug = 'mus')),
('Hasköy', 'haskoy', (SELECT id FROM cities WHERE slug = 'mus')),
('Korkut', 'korkut', (SELECT id FROM cities WHERE slug = 'mus')),
('Malazgirt', 'malazgirt', (SELECT id FROM cities WHERE slug = 'mus')),
('Merkez', 'merkez-mus', (SELECT id FROM cities WHERE slug = 'mus')),
('Varto', 'varto', (SELECT id FROM cities WHERE slug = 'mus')),

-- NEVŞEHİR (8 ilçe)
('Acıgöl', 'acigol', (SELECT id FROM cities WHERE slug = 'nevsehir')),
('Avanos', 'avanos', (SELECT id FROM cities WHERE slug = 'nevsehir')),
('Derinkuyu', 'derinkuyu', (SELECT id FROM cities WHERE slug = 'nevsehir')),
('Gülşehir', 'gulsehir', (SELECT id FROM cities WHERE slug = 'nevsehir')),
('Hacıbektaş', 'hacibektas', (SELECT id FROM cities WHERE slug = 'nevsehir')),
('Kozaklı', 'kozakli', (SELECT id FROM cities WHERE slug = 'nevsehir')),
('Merkez', 'merkez-nevsehir', (SELECT id FROM cities WHERE slug = 'nevsehir')),
('Ürgüp', 'urgup', (SELECT id FROM cities WHERE slug = 'nevsehir')),

-- NİĞDE (6 ilçe)
('Altunhisar', 'altunhisar', (SELECT id FROM cities WHERE slug = 'nigde')),
('Bor', 'bor', (SELECT id FROM cities WHERE slug = 'nigde')),
('Çamardı', 'camardi', (SELECT id FROM cities WHERE slug = 'nigde')),
('Çiftlik', 'ciftlik', (SELECT id FROM cities WHERE slug = 'nigde')),
('Merkez', 'merkez-nigde', (SELECT id FROM cities WHERE slug = 'nigde')),
('Ulukışla', 'ulukisla', (SELECT id FROM cities WHERE slug = 'nigde')),

-- ORDU (19 ilçe)
('Akkuş', 'akkus', (SELECT id FROM cities WHERE slug = 'ordu')),
('Altınordu', 'altinordu', (SELECT id FROM cities WHERE slug = 'ordu')),
('Aybastı', 'aybasti', (SELECT id FROM cities WHERE slug = 'ordu')),
('Çamaş', 'camas', (SELECT id FROM cities WHERE slug = 'ordu')),
('Çatalpınar', 'catalpinar', (SELECT id FROM cities WHERE slug = 'ordu')),
('Çaybaşı', 'caybasi', (SELECT id FROM cities WHERE slug = 'ordu')),
('Fatsa', 'fatsa', (SELECT id FROM cities WHERE slug = 'ordu')),
('Gölköy', 'golkoy', (SELECT id FROM cities WHERE slug = 'ordu')),
('Gülyalı', 'gulyali', (SELECT id FROM cities WHERE slug = 'ordu')),
('Gürgentepe', 'gurgentepe', (SELECT id FROM cities WHERE slug = 'ordu')),
('İkizce', 'ikizce', (SELECT id FROM cities WHERE slug = 'ordu')),
('Kabadüz', 'kabaduz', (SELECT id FROM cities WHERE slug = 'ordu')),
('Kabataş', 'kabatas', (SELECT id FROM cities WHERE slug = 'ordu')),
('Korgan', 'korgan', (SELECT id FROM cities WHERE slug = 'ordu')),
('Kumru', 'kumru', (SELECT id FROM cities WHERE slug = 'ordu')),
('Mesudiye', 'mesudiye', (SELECT id FROM cities WHERE slug = 'ordu')),
('Perşembe', 'persembe', (SELECT id FROM cities WHERE slug = 'ordu')),
('Ulubey', 'ulubey-ordu', (SELECT id FROM cities WHERE slug = 'ordu')),
('Ünye', 'unye', (SELECT id FROM cities WHERE slug = 'ordu')),

-- OSMANİYE (7 ilçe)
('Bahçe', 'bahce', (SELECT id FROM cities WHERE slug = 'osmaniye')),
('Düziçi', 'duzici', (SELECT id FROM cities WHERE slug = 'osmaniye')),
('Hasanbeyli', 'hasanbeyli', (SELECT id FROM cities WHERE slug = 'osmaniye')),
('Kadirli', 'kadirli', (SELECT id FROM cities WHERE slug = 'osmaniye')),
('Merkez', 'merkez-osmaniye', (SELECT id FROM cities WHERE slug = 'osmaniye')),
('Sumbas', 'sumbas', (SELECT id FROM cities WHERE slug = 'osmaniye')),
('Toprakkale', 'toprakkale', (SELECT id FROM cities WHERE slug = 'osmaniye')),

-- RİZE (12 ilçe)
('Ardeşen', 'ardesen', (SELECT id FROM cities WHERE slug = 'rize')),
('Çamlıhemşin', 'camlihemin', (SELECT id FROM cities WHERE slug = 'rize')),
('Çayeli', 'cayeli', (SELECT id FROM cities WHERE slug = 'rize')),
('Derepazarı', 'derepazari', (SELECT id FROM cities WHERE slug = 'rize')),
('Fındıklı', 'findikli', (SELECT id FROM cities WHERE slug = 'rize')),
('Güneysu', 'guneysu', (SELECT id FROM cities WHERE slug = 'rize')),
('Hemşin', 'hemsin', (SELECT id FROM cities WHERE slug = 'rize')),
('İkizdere', 'ikizdere', (SELECT id FROM cities WHERE slug = 'rize')),
('İyidere', 'iyidere', (SELECT id FROM cities WHERE slug = 'rize')),
('Kalkandere', 'kalkandere', (SELECT id FROM cities WHERE slug = 'rize')),
('Merkez', 'merkez-rize', (SELECT id FROM cities WHERE slug = 'rize')),
('Pazar', 'pazar-rize', (SELECT id FROM cities WHERE slug = 'rize')),

-- SAKARYA (16 ilçe)
('Adapazarı', 'adapazari', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Akyazı', 'akyazi', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Arifiye', 'arifiye', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Erenler', 'erenler', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Ferizli', 'ferizli', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Geyve', 'geyve', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Hendek', 'hendek', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Karapürçek', 'karapurcek', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Karasu', 'karasu', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Kaynarca', 'kaynarca', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Kocaali', 'kocaali', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Pamukova', 'pamukova', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Sapanca', 'sapanca', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Serdivan', 'serdivan', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Söğütlü', 'sogutlu', (SELECT id FROM cities WHERE slug = 'sakarya')),
('Taraklı', 'tarakli', (SELECT id FROM cities WHERE slug = 'sakarya')),

-- SAMSUN (17 ilçe)
('19 Mayıs', '19-mayis', (SELECT id FROM cities WHERE slug = 'samsun')),
('Alaçam', 'alacam', (SELECT id FROM cities WHERE slug = 'samsun')),
('Asarcık', 'asarcik', (SELECT id FROM cities WHERE slug = 'samsun')),
('Atakum', 'atakum', (SELECT id FROM cities WHERE slug = 'samsun')),
('Ayvacık', 'ayvacik-samsun', (SELECT id FROM cities WHERE slug = 'samsun')),
('Bafra', 'bafra', (SELECT id FROM cities WHERE slug = 'samsun')),
('Canik', 'canik', (SELECT id FROM cities WHERE slug = 'samsun')),
('Çarşamba', 'carsamba', (SELECT id FROM cities WHERE slug = 'samsun')),
('Havza', 'havza', (SELECT id FROM cities WHERE slug = 'samsun')),
('İlkadım', 'ilkadim', (SELECT id FROM cities WHERE slug = 'samsun')),
('Kavak', 'kavak', (SELECT id FROM cities WHERE slug = 'samsun')),
('Ladik', 'ladik', (SELECT id FROM cities WHERE slug = 'samsun')),
('Salıpazarı', 'salipazari', (SELECT id FROM cities WHERE slug = 'samsun')),
('Tekkeköy', 'tekkekoy', (SELECT id FROM cities WHERE slug = 'samsun')),
('Terme', 'terme', (SELECT id FROM cities WHERE slug = 'samsun')),
('Vezirköprü', 'vezirkopru', (SELECT id FROM cities WHERE slug = 'samsun')),
('Yakakent', 'yakakent', (SELECT id FROM cities WHERE slug = 'samsun')),

-- ŞANLIURFA (13 ilçe)
('Akçakale', 'akcakale', (SELECT id FROM cities WHERE slug = 'sanliurfa')),
('Birecik', 'birecik', (SELECT id FROM cities WHERE slug = 'sanliurfa')),
('Bozova', 'bozova', (SELECT id FROM cities WHERE slug = 'sanliurfa')),
('Ceylanpınar', 'ceylanpinar', (SELECT id FROM cities WHERE slug = 'sanliurfa')),
('Eyyübiye', 'eyyubiye', (SELECT id FROM cities WHERE slug = 'sanliurfa')),
('Halfeti', 'halfeti', (SELECT id FROM cities WHERE slug = 'sanliurfa')),
('Haliliye', 'haliliye', (SELECT id FROM cities WHERE slug = 'sanliurfa')),
('Harran', 'harran', (SELECT id FROM cities WHERE slug = 'sanliurfa')),
('Hilvan', 'hilvan', (SELECT id FROM cities WHERE slug = 'sanliurfa')),
('Karaköprü', 'karakopru', (SELECT id FROM cities WHERE slug = 'sanliurfa')),
('Siverek', 'siverek', (SELECT id FROM cities WHERE slug = 'sanliurfa')),
('Suruç', 'suruc', (SELECT id FROM cities WHERE slug = 'sanliurfa')),
('Viranşehir', 'viransehir', (SELECT id FROM cities WHERE slug = 'sanliurfa')),

-- SİİRT (7 ilçe)
('Baykan', 'baykan', (SELECT id FROM cities WHERE slug = 'siirt')),
('Eruh', 'eruh', (SELECT id FROM cities WHERE slug = 'siirt')),
('Kurtalan', 'kurtalan', (SELECT id FROM cities WHERE slug = 'siirt')),
('Merkez', 'merkez-siirt', (SELECT id FROM cities WHERE slug = 'siirt')),
('Pervari', 'pervari', (SELECT id FROM cities WHERE slug = 'siirt')),
('Şirvan', 'sirvan', (SELECT id FROM cities WHERE slug = 'siirt')),
('Tillo', 'tillo', (SELECT id FROM cities WHERE slug = 'siirt')),

-- SİNOP (9 ilçe)
('Ayancık', 'ayancik', (SELECT id FROM cities WHERE slug = 'sinop')),
('Boyabat', 'boyabat', (SELECT id FROM cities WHERE slug = 'sinop')),
('Dikmen', 'dikmen', (SELECT id FROM cities WHERE slug = 'sinop')),
('Durağan', 'duragan', (SELECT id FROM cities WHERE slug = 'sinop')),
('Erfelek', 'erfelek', (SELECT id FROM cities WHERE slug = 'sinop')),
('Gerze', 'gerze', (SELECT id FROM cities WHERE slug = 'sinop')),
('Merkez', 'merkez-sinop', (SELECT id FROM cities WHERE slug = 'sinop')),
('Saraydüzü', 'sarayduzu', (SELECT id FROM cities WHERE slug = 'sinop')),
('Türkeli', 'turkeli', (SELECT id FROM cities WHERE slug = 'sinop')),

-- ŞIRNAK (7 ilçe)
('Beytüşşebap', 'beytussebap', (SELECT id FROM cities WHERE slug = 'sirnak')),
('Cizre', 'cizre', (SELECT id FROM cities WHERE slug = 'sirnak')),
('Güçlükonak', 'guclukonak', (SELECT id FROM cities WHERE slug = 'sirnak')),
('İdil', 'idil', (SELECT id FROM cities WHERE slug = 'sirnak')),
('Merkez', 'merkez-sirnak', (SELECT id FROM cities WHERE slug = 'sirnak')),
('Silopi', 'silopi', (SELECT id FROM cities WHERE slug = 'sirnak')),
('Uludere', 'uludere', (SELECT id FROM cities WHERE slug = 'sirnak')),

-- SİVAS (17 ilçe)
('Akıncılar', 'akincilar', (SELECT id FROM cities WHERE slug = 'sivas')),
('Altınyayla', 'altinyayla-sivas', (SELECT id FROM cities WHERE slug = 'sivas')),
('Divriği', 'divrigi', (SELECT id FROM cities WHERE slug = 'sivas')),
('Doğanşar', 'dogansar', (SELECT id FROM cities WHERE slug = 'sivas')),
('Gemerek', 'gemerek', (SELECT id FROM cities WHERE slug = 'sivas')),
('Gölova', 'golova', (SELECT id FROM cities WHERE slug = 'sivas')),
('Gürün', 'gurun', (SELECT id FROM cities WHERE slug = 'sivas')),
('Hafik', 'hafik', (SELECT id FROM cities WHERE slug = 'sivas')),
('İmranlı', 'imranli', (SELECT id FROM cities WHERE slug = 'sivas')),
('Kangal', 'kangal', (SELECT id FROM cities WHERE slug = 'sivas')),
('Koyulhisar', 'koyulhisar', (SELECT id FROM cities WHERE slug = 'sivas')),
('Merkez', 'merkez-sivas', (SELECT id FROM cities WHERE slug = 'sivas')),
('Şarkışla', 'sarkisla', (SELECT id FROM cities WHERE slug = 'sivas')),
('Suşehri', 'susehri', (SELECT id FROM cities WHERE slug = 'sivas')),
('Ulaş', 'ulas', (SELECT id FROM cities WHERE slug = 'sivas')),
('Yıldızeli', 'yildizeli', (SELECT id FROM cities WHERE slug = 'sivas')),
('Zara', 'zara', (SELECT id FROM cities WHERE slug = 'sivas')),

-- TEKİRDAĞ (11 ilçe)
('Çerkezköy', 'cerkezkoy', (SELECT id FROM cities WHERE slug = 'tekirdag')),
('Çorlu', 'corlu', (SELECT id FROM cities WHERE slug = 'tekirdag')),
('Ergene', 'ergene', (SELECT id FROM cities WHERE slug = 'tekirdag')),
('Hayrabolu', 'hayrabolu', (SELECT id FROM cities WHERE slug = 'tekirdag')),
('Kapaklı', 'kapakli', (SELECT id FROM cities WHERE slug = 'tekirdag')),
('Malkara', 'malkara', (SELECT id FROM cities WHERE slug = 'tekirdag')),
('Marmaraereğlisi', 'marmaraereglis i', (SELECT id FROM cities WHERE slug = 'tekirdag')),
('Muratlı', 'muratli', (SELECT id FROM cities WHERE slug = 'tekirdag')),
('Saray', 'saray', (SELECT id FROM cities WHERE slug = 'tekirdag')),
('Süleymanpaşa', 'suleymampasa', (SELECT id FROM cities WHERE slug = 'tekirdag')),
('Şarköy', 'sarkoy', (SELECT id FROM cities WHERE slug = 'tekirdag')),

-- TOKAT (12 ilçe)
('Almus', 'almus', (SELECT id FROM cities WHERE slug = 'tokat')),
('Artova', 'artova', (SELECT id FROM cities WHERE slug = 'tokat')),
('Başçiftlik', 'basciftlik', (SELECT id FROM cities WHERE slug = 'tokat')),
('Erbaa', 'erbaa', (SELECT id FROM cities WHERE slug = 'tokat')),
('Merkez', 'merkez-tokat', (SELECT id FROM cities WHERE slug = 'tokat')),
('Niksar', 'niksar', (SELECT id FROM cities WHERE slug = 'tokat')),
('Pazar', 'pazar-tokat', (SELECT id FROM cities WHERE slug = 'tokat')),
('Reşadiye', 'resadiye', (SELECT id FROM cities WHERE slug = 'tokat')),
('Sulusaray', 'sulusaray', (SELECT id FROM cities WHERE slug = 'tokat')),
('Turhal', 'turhal', (SELECT id FROM cities WHERE slug = 'tokat')),
('Yeşilyurt', 'yesilyurt-tokat', (SELECT id FROM cities WHERE slug = 'tokat')),
('Zile', 'zile', (SELECT id FROM cities WHERE slug = 'tokat')),

-- TRABZON (18 ilçe)
('Akçaabat', 'akcaabat', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Araklı', 'arakli', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Arsin', 'arsin', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Beşikdüzü', 'besikduzu', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Çarşıbaşı', 'carsibasi', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Çaykara', 'caykara', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Dernekpazarı', 'dernekpazari', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Düzköy', 'duzkoy', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Hayrat', 'hayrat', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Köprübaşı', 'koprubasi-trabzon', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Maçka', 'macka', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Of', 'of', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Ortahisar', 'ortahisar', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Şalpazarı', 'salpazari', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Sürmene', 'surmene', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Tonya', 'tonya', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Vakfıkebir', 'vakfikebir', (SELECT id FROM cities WHERE slug = 'trabzon')),
('Yomra', 'yomra', (SELECT id FROM cities WHERE slug = 'trabzon')),

-- TUNCELİ (8 ilçe)
('Çemişgezek', 'cemisgezek', (SELECT id FROM cities WHERE slug = 'tunceli')),
('Hozat', 'hozat', (SELECT id FROM cities WHERE slug = 'tunceli')),
('Mazgirt', 'mazgirt', (SELECT id FROM cities WHERE slug = 'tunceli')),
('Merkez', 'merkez-tunceli', (SELECT id FROM cities WHERE slug = 'tunceli')),
('Nazımiye', 'nazimiye', (SELECT id FROM cities WHERE slug = 'tunceli')),
('Ovacık', 'ovacik-tunceli', (SELECT id FROM cities WHERE slug = 'tunceli')),
('Pertek', 'pertek', (SELECT id FROM cities WHERE slug = 'tunceli')),
('Pülümür', 'pulumur', (SELECT id FROM cities WHERE slug = 'tunceli')),

-- UŞAK (6 ilçe)
('Banaz', 'banaz', (SELECT id FROM cities WHERE slug = 'usak')),
('Eşme', 'esme', (SELECT id FROM cities WHERE slug = 'usak')),
('Karahallı', 'karahalli', (SELECT id FROM cities WHERE slug = 'usak')),
('Merkez', 'merkez-usak', (SELECT id FROM cities WHERE slug = 'usak')),
('Sivaslı', 'sivasli', (SELECT id FROM cities WHERE slug = 'usak')),
('Ulubey', 'ulubey-usak', (SELECT id FROM cities WHERE slug = 'usak')),

-- VAN (13 ilçe)
('Bahçesaray', 'bahcesaray', (SELECT id FROM cities WHERE slug = 'van')),
('Başkale', 'baskale', (SELECT id FROM cities WHERE slug = 'van')),
('Çaldıran', 'caldiran', (SELECT id FROM cities WHERE slug = 'van')),
('Çatak', 'catak', (SELECT id FROM cities WHERE slug = 'van')),
('Edremit', 'edremit-van', (SELECT id FROM cities WHERE slug = 'van')),
('Erciş', 'ercis', (SELECT id FROM cities WHERE slug = 'van')),
('Gevaş', 'gevas', (SELECT id FROM cities WHERE slug = 'van')),
('Gürpınar', 'gurpinar', (SELECT id FROM cities WHERE slug = 'van')),
('İpekyolu', 'ipekyolu', (SELECT id FROM cities WHERE slug = 'van')),
('Muradiye', 'muradiye', (SELECT id FROM cities WHERE slug = 'van')),
('Özalp', 'ozalp', (SELECT id FROM cities WHERE slug = 'van')),
('Saray', 'saray-van', (SELECT id FROM cities WHERE slug = 'van')),
('Tuşba', 'tusba', (SELECT id FROM cities WHERE slug = 'van')),

-- YALOVA (6 ilçe)
('Altınova', 'altinova', (SELECT id FROM cities WHERE slug = 'yalova')),
('Armutlu', 'armutlu', (SELECT id FROM cities WHERE slug = 'yalova')),
('Çınarcık', 'cinarcik', (SELECT id FROM cities WHERE slug = 'yalova')),
('Çiftlikköy', 'ciftlikkoy', (SELECT id FROM cities WHERE slug = 'yalova')),
('Merkez', 'merkez-yalova', (SELECT id FROM cities WHERE slug = 'yalova')),
('Termal', 'termal', (SELECT id FROM cities WHERE slug = 'yalova')),

-- YOZGAT (14 ilçe)
('Akdağmadeni', 'akdagmadeni', (SELECT id FROM cities WHERE slug = 'yozgat')),
('Aydıncık', 'aydincik-yozgat', (SELECT id FROM cities WHERE slug = 'yozgat')),
('Boğazlıyan', 'bogazliyan', (SELECT id FROM cities WHERE slug = 'yozgat')),
('Çandır', 'candir', (SELECT id FROM cities WHERE slug = 'yozgat')),
('Çayıralan', 'cayiralan', (SELECT id FROM cities WHERE slug = 'yozgat')),
('Çekerek', 'cekerek', (SELECT id FROM cities WHERE slug = 'yozgat')),
('Kadışehri', 'kadisehri', (SELECT id FROM cities WHERE slug = 'yozgat')),
('Merkez', 'merkez-yozgat', (SELECT id FROM cities WHERE slug = 'yozgat')),
('Saraykent', 'saraykent', (SELECT id FROM cities WHERE slug = 'yozgat')),
('Sarıkaya', 'sarikaya', (SELECT id FROM cities WHERE slug = 'yozgat')),
('Sorgun', 'sorgun', (SELECT id FROM cities WHERE slug = 'yozgat')),
('Şefaatli', 'sefaatli', (SELECT id FROM cities WHERE slug = 'yozgat')),
('Yenifakılı', 'yenifakili', (SELECT id FROM cities WHERE slug = 'yozgat')),
('Yerköy', 'yerkoy', (SELECT id FROM cities WHERE slug = 'yozgat')),

-- ZONGULDAK (8 ilçe)
('Alaplı', 'alapli', (SELECT id FROM cities WHERE slug = 'zonguldak')),
('Çaycuma', 'caycuma', (SELECT id FROM cities WHERE slug = 'zonguldak')),
('Devrek', 'devrek', (SELECT id FROM cities WHERE slug = 'zonguldak')),
('Ereğli', 'eregli-zonguldak', (SELECT id FROM cities WHERE slug = 'zonguldak')),
('Gökçebey', 'gokcebey', (SELECT id FROM cities WHERE slug = 'zonguldak')),
('Kilimli', 'kilimli', (SELECT id FROM cities WHERE slug = 'zonguldak')),
('Kozlu', 'kozlu', (SELECT id FROM cities WHERE slug = 'zonguldak')),
('Merkez', 'merkez-zonguldak', (SELECT id FROM cities WHERE slug = 'zonguldak'))

ON CONFLICT (city_id, slug) DO NOTHING;

-- Display success message
SELECT
  'İLÇELER BAŞARIYLA EKLENDİ!' as durum,
  (SELECT COUNT(*) FROM districts) as ilce_sayisi,
  (SELECT COUNT(DISTINCT city_id) FROM districts) as sehir_sayisi;
