-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.applications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  job_id uuid NOT NULL,
  candidate_id uuid,
  status text DEFAULT 'pending'::text,
  cover_letter text,
  resume_url text,
  applied_at timestamp with time zone DEFAULT now(),
  reviewed_at timestamp with time zone,
  notes text,
  guest_name text,
  guest_email text,
  guest_phone text,
  contact_preference text DEFAULT 'email'::text CHECK (contact_preference = ANY (ARRAY['email'::text, 'phone'::text])),
  cv_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT applications_pkey PRIMARY KEY (id),
  CONSTRAINT applications_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT applications_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES public.candidate_profiles(id)
);
CREATE TABLE public.candidate_profiles (
  id uuid NOT NULL,
  title text,
  bio text,
  date_of_birth date,
  gender text,
  city text,
  experience_years integer,
  education_level USER-DEFINED,
  skills ARRAY,
  languages jsonb,
  resume_url text,
  linkedin_url text,
  portfolio_url text,
  is_open_to_work boolean DEFAULT true,
  preferred_work_types ARRAY,
  preferred_locations ARRAY,
  expected_salary_min integer,
  expected_salary_max integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT candidate_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT candidate_profiles_id_fkey FOREIGN KEY (id) REFERENCES public.profiles(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text,
  icon text,
  parent_id uuid,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id)
);
CREATE TABLE public.cities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  latitude numeric,
  longitude numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cities_pkey PRIMARY KEY (id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  owner_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  website text,
  logo_url text,
  company_size USER-DEFINED,
  industry text,
  founded_year integer,
  address text,
  city text,
  country text DEFAULT 'TR'::text,
  phone text,
  email text,
  is_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  subscription_tier USER-DEFINED DEFAULT 'free'::subscription_tier,
  job_post_limit integer DEFAULT 3,
  active_job_posts integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  city_id uuid,
  sector text,
  employee_count text,
  linkedin text,
  twitter text,
  instagram text,
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id),
  CONSTRAINT companies_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id)
);
CREATE TABLE public.districts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL,
  city_id uuid NOT NULL,
  latitude numeric,
  longitude numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT districts_pkey PRIMARY KEY (id),
  CONSTRAINT districts_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id)
);
CREATE TABLE public.educations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  candidate_id uuid NOT NULL,
  school_name text NOT NULL,
  department text,
  degree text NOT NULL CHECK (degree = ANY (ARRAY['high_school'::text, 'associate'::text, 'bachelor'::text, 'master'::text, 'doctorate'::text])),
  description text,
  start_date date NOT NULL,
  end_date date,
  is_current boolean DEFAULT false,
  gpa numeric,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT educations_pkey PRIMARY KEY (id),
  CONSTRAINT educations_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES public.candidate_profiles(id)
);
CREATE TABLE public.experiences (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  candidate_id uuid NOT NULL,
  company_name text NOT NULL,
  position text NOT NULL,
  description text,
  start_date date NOT NULL,
  end_date date,
  is_current boolean DEFAULT false,
  location text,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT experiences_pkey PRIMARY KEY (id),
  CONSTRAINT experiences_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES public.candidate_profiles(id)
);
CREATE TABLE public.favorites (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  job_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT favorites_pkey PRIMARY KEY (id),
  CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT favorites_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.job_categories (
  job_id uuid NOT NULL,
  category_id uuid NOT NULL,
  CONSTRAINT job_categories_pkey PRIMARY KEY (job_id, category_id),
  CONSTRAINT job_categories_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  title text NOT NULL,
  slug text NOT NULL,
  description text NOT NULL,
  requirements text,
  benefits ARRAY,
  status USER-DEFINED DEFAULT 'draft'::job_status,
  work_type USER-DEFINED,
  experience_level USER-DEFINED,
  education_level USER-DEFINED,
  salary_min integer,
  salary_max integer,
  salary_currency text DEFAULT 'TRY'::text,
  show_salary boolean DEFAULT false,
  location_city text NOT NULL,
  location_district text,
  is_remote boolean DEFAULT false,
  application_deadline timestamp with time zone,
  view_count integer DEFAULT 0,
  application_count integer DEFAULT 0,
  phone_reveal_count integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  featured_until timestamp with time zone,
  published_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  district_id uuid,
  additional_info text,
  responsibilities text,
  qualifications text,
  address text,
  category_id uuid,
  city_id uuid,
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT jobs_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id),
  CONSTRAINT jobs_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT jobs_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id)
);
CREATE TABLE public.phone_reveals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  job_id uuid NOT NULL,
  user_id uuid,
  ip_address text,
  user_agent text,
  revealed_at timestamp with time zone DEFAULT now(),
  revealed_date date DEFAULT CURRENT_DATE,
  CONSTRAINT phone_reveals_pkey PRIMARY KEY (id),
  CONSTRAINT phone_reveals_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT phone_reveals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'candidate'::user_role,
  email text NOT NULL UNIQUE,
  full_name text,
  phone text,
  avatar_url text,
  is_active boolean DEFAULT true,
  subscription_tier USER-DEFINED DEFAULT 'free'::subscription_tier,
  subscription_expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);